version: "3.8"

services:
 
  ###################################
  # student: The Student microservice
  ###################################
  student:
    build:
      context: ./
      dockerfile: student\student.Dockerfile
    image: student:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/student
      PYTHONUNBUFFERED: 1

  ###################################
  # job: The Job microservice
  ###################################
  job:
    build:
      context: ./
      dockerfile: job\job.Dockerfile
    image: job:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/job
      PYTHONUNBUFFERED: 1

  ###################################
  # module: The module microservice
  ###################################
  module:
    build:
      context: ./
      dockerfile: module\module.Dockerfile
    image: module:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/module
      PYTHONUNBUFFERED: 1

  ###############################################
  # Match job: The Match job microservice
  ###############################################
  match_job:
    build:
      context: ./
      dockerfile: match_job\match_job.Dockerfile
    image: match_job:1.0
    restart: always
    depends_on:
      - student
      - module
      - job
    environment:
      student_URL: http://student:5001/
      module_URL: http://module:5000/
      job_URL: http://job:5002/
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"