version: "3.8"

volumes:
  rabbitmq_data:
  
services:
 
  ###################################
  # student: The Student microservice
  ###################################
  student:
    build:
      context: ./
      dockerfile: ./student.Dockerfile
    image: student:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/student
      PYTHONUNBUFFERED: 1

  ###################################
  # job: The Job microservice
  ###################################
  job:
    build:
      context: ./
      dockerfile: ./job.Dockerfile
    image: job:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/job
      PYTHONUNBUFFERED: 1

  ###################################
  # module: The module microservice
  ###################################
  module:
    build:
      context: ./
      dockerfile: ./module.Dockerfile
    image: module:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/module
      PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq


  ###############################################
  # Match job: The Match job microservice
  ###############################################
  match_job:
    build:
      context: ./
      dockerfile: ./match_job.Dockerfile
    image: match_job:1.0
    restart: always
    depends_on:
      - student
      - module
      - job
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      student_URL: http://student:5001/
      module_URL: http://module:5000/
      job_URL: http://job:5002/
      PYTHONUNBUFFERED: 1
    ports:
      - "5005:5005"